### ISSUE TITLE
Readme example doesn't actually demonstrate plugin use

### ISSUE THREAD

**Issue by AKST** [squarewolf/gulp-neuter#7]
This is the example in the readme at the moment. 
```
var neuter = require('gulp-neuter');

gulp.task('templates', function(){
  gulp.src(['js/main.js'])
    .pipe(handlebars())
    .pipe(gulp.dest('build/templates/'));
})
```
It imports the plugin, but it doesn't demonstrate it's usage. There is however an example of the handlebars plugin, which is interesting, but I'm not sure that is intentional. I'd make a PR, but I'm not entirely sure how to use this gulp-plugin yet.

**Comment by tvervest** [comment]
This has been fixed since commit a872e2292afc0d786031d22c0df5db90a28bdfe3, hope this helps!
